"""add total_tokens fields

Revision ID: 5a8c3d7e9f12
Revises: 4ff3f0ad8020
Create Date: 2026-10-08 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a8c3d7e9f12'
down_revision = '4ff3f0ad8020'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('gen_total_tokens', sa.Integer(), nullable=True))
    op.add_column('lesson_exercises', sa.Column('eval_total_tokens', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lesson_exercises', 'eval_total_tokens')
    op.drop_column('lessons', 'gen_total_tokens')
    # ### end Alembic commands ###