"""Initial schema

Revision ID: e415bc2a09fb
Revises: 
Create Date: 2026-10-07 12:44:21.919607

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e415bc2a09fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('llm_calls',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('purpose', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('lesson_id', sa.BigInteger(), nullable=True),
    sa.Column('exercise_id', sa.BigInteger(), nullable=True),
    sa.Column('attempt', sa.SmallInteger(), nullable=False),
    sa.Column('request', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), nullable=False),
    sa.Column('response_raw', sa.Text(), nullable=True),
    sa.Column('response_json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('http_status', sa.SmallInteger(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('timezone_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_onboarded', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('level', sa.String(length=2), nullable=True),
    sa.Column('dictionary_code', sa.String(length=32), nullable=True),
    sa.Column('words_per_lesson', sa.SmallInteger(), nullable=False),
    sa.Column('daily_lesson_limit', sa.SmallInteger(), nullable=False),
    sa.Column('last_lesson_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('words',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('lemma', sa.String(length=64), nullable=False),
    sa.Column('lemma_key', sa.String(length=64), nullable=False),
    sa.Column('pos', sa.String(length=10), nullable=False),
    sa.Column('level', sa.String(length=2), nullable=True),
    sa.Column('translations', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('in_general', sa.Boolean(), nullable=False),
    sa.Column('in_it', sa.Boolean(), nullable=False),
    sa.Column('in_travel', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lemma_key', 'pos', name='uq_words_lemma_key_pos')
    )
    op.create_index('ix_words_level_general', 'words', ['level'], unique=False, postgresql_where=sa.text('in_general = true'))
    op.create_index('ix_words_level_it', 'words', ['level'], unique=False, postgresql_where=sa.text('in_it = true'))
    op.create_index('ix_words_level_travel', 'words', ['level'], unique=False, postgresql_where=sa.text('in_travel = true'))
    op.create_table('auth_sessions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_auth_sessions_expires_at', 'auth_sessions', ['expires_at'], unique=False)
    op.create_index('ix_auth_sessions_user_id', 'auth_sessions', ['user_id'], unique=False)
    op.create_table('lessons',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('lesson_number', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_local_date', sa.Date(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_local_date', sa.Date(), nullable=True),
    sa.Column('gen_prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('gen_completion_tokens', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'idempotency_key', name='uq_lessons_user_idem_key'),
    sa.UniqueConstraint('user_id', 'lesson_number', name='uq_lessons_user_number')
    )
    op.create_index('ix_lessons_user_completed', 'lessons', ['user_id', 'completed_local_date'], unique=False)
    op.create_index('ix_lessons_user_in_progress', 'lessons', ['user_id'], unique=True, postgresql_where=sa.text("status = 'in_progress'"))
    op.create_index('ix_lessons_user_started', 'lessons', ['user_id', 'started_local_date'], unique=False)
    op.create_table('prompts',
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('system_template', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('user_words',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('word_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('stage', sa.SmallInteger(), nullable=False),
    sa.Column('due_lesson_number', sa.Integer(), nullable=True),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'word_id', name='uq_user_words_user_word')
    )
    op.create_index('ix_user_words_user_due_active', 'user_words', ['user_id', 'due_lesson_number'], unique=False, postgresql_where=sa.text("status = 'active'"))
    op.create_index('ix_user_words_user_status_due', 'user_words', ['user_id', 'status', 'due_lesson_number'], unique=False)
    op.create_table('lesson_exercises',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('lesson_id', sa.BigInteger(), nullable=False),
    sa.Column('order_index', sa.SmallInteger(), nullable=False),
    sa.Column('target_sentence', sa.String(length=200), nullable=False),
    sa.Column('reference_translation', sa.String(length=300), nullable=False),
    sa.Column('user_translation', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('target_words', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), nullable=False),
    sa.Column('suggested_words', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), nullable=False),
    sa.Column('nontarget_words', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), nullable=False),
    sa.Column('eval_prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('eval_completion_tokens', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lesson_id', 'order_index', name='uq_exercises_lesson_order')
    )
    op.create_index('ix_exercises_pending', 'lesson_exercises', ['lesson_id', 'order_index'], unique=False, postgresql_where=sa.text("status = 'pending'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_exercises_pending', table_name='lesson_exercises', postgresql_where=sa.text("status = 'pending'"))
    op.drop_table('lesson_exercises')
    op.drop_index('ix_user_words_user_status_due', table_name='user_words')
    op.drop_index('ix_user_words_user_due_active', table_name='user_words', postgresql_where=sa.text("status = 'active'"))
    op.drop_table('user_words')
    op.drop_table('prompts')
    op.drop_index('ix_lessons_user_started', table_name='lessons')
    op.drop_index('ix_lessons_user_in_progress', table_name='lessons', postgresql_where=sa.text("status = 'in_progress'"))
    op.drop_index('ix_lessons_user_completed', table_name='lessons')
    op.drop_table('lessons')
    op.drop_index('ix_auth_sessions_user_id', table_name='auth_sessions')
    op.drop_index('ix_auth_sessions_expires_at', table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_index('ix_words_level_travel', table_name='words', postgresql_where=sa.text('in_travel = true'))
    op.drop_index('ix_words_level_it', table_name='words', postgresql_where=sa.text('in_it = true'))
    op.drop_index('ix_words_level_general', table_name='words', postgresql_where=sa.text('in_general = true'))
    op.drop_table('words')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('llm_calls')
    op.drop_table('events')
    # ### end Alembic commands ###